const REALLY_LONG_CONSTANT_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = 1
const REALLY_LONG_CONSTANT_BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB = 1
const REALLY_LONG_CONSTANT_CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC = 1
const REALLY_LONG_CONSTANT_DDDDDDDDDD = 1
const REALLY_LONG_CONSTANT_EEEEEEEEEE = 1


func my_func_a(a):
	match a:
		REALLY_LONG_CONSTANT_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, \
		REALLY_LONG_CONSTANT_BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB, \
		REALLY_LONG_CONSTANT_CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC:
			pass
		REALLY_LONG_CONSTANT_DDDDDDDDDD, REALLY_LONG_CONSTANT_EEEEEEEEEE:
			pass


func my_func_b(a):
	match a:
		REALLY_LONG_CONSTANT_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, \
		REALLY_LONG_CONSTANT_BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB, \
		REALLY_LONG_CONSTANT_DDDDDDDDDD, \
		REALLY_LONG_CONSTANT_EEEEEEEEEE:
			pass
		REALLY_LONG_CONSTANT_CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC:
			pass
